sudo: required

language: python

services:
  - docker

before_script:
  sudo chown -R 1000:1000 $TRAVIS_BUILD_DIR

script: 
  cd Behavior && ./test.sh
  cd Behavior/Tests/Utilities/Waveform && ./test.sh